### ISSUE TITLE
Getting error while importing 2205 projects into eclipse.

### ISSUE THREAD

**Issue by jobinbabu** [SAP/hybris-commerce-eclipse-plugin#108]
Getting the below error while importing projects from 2205

An internal error occurred during: "Importing Commerce Project".
de/hybris/bootstrap/config/SystemConfig has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0

Version: 2022-03 (4.23.0)
Build id: 20220310-1457

**Comment by mikolayek** [comment]
Hi there. issue has been documented with older jvm, but caused by the same issue. meaning eclipse is using older jvm than your project. https://github.com/SAP/hybris-commerce-eclipse-plugin/blob/master/docs/kb/info.md

**Comment by mikolayek** [comment]
closing due to no response
