### ISSUE TITLE
Empty "Attach Sources" pane during import wizard

### ISSUE THREAD

**Issue by uni1811** [SAP/hybris-commerce-eclipse-plugin#16]
During the import process there appears an empty "Attach Sources" pane.

OS: Windows 10
Eclipse: Neon.3 Release (4.6.3)

![image](https://user-images.githubusercontent.com/30926161/29209270-eeff50b2-7e8d-11e7-9ae8-88c014f8ef78.png)

**Comment by brendandobbs** [comment]
Should be fixed in latest 1.4 release
