### ISSUE TITLE
StartStopThreads duplicated in server.xml for 6.7

### ISSUE THREAD

**Issue by brendandobbs** [SAP/hybris-commerce-eclipse-plugin#28]
Version 6.7 and higher has StartStopThreads already added to server.xml. We need to either check if the StartStopThreads setting already exists or don't do any changes for >=6.7

**Comment by ravishankar-gaddamidi** [comment]
is this issue will be fixed? this plug in is useful, but without this fix its creating manual work, we have to open server.xml and remove the duplicate entry.
request attention here.

**Comment by mikolayek** [comment]
Hi there, yep. bug has been reproduced and will be fixed soon. Thanks for raising issue.
