### ISSUE TITLE
Impex formatting breaking on eclipse oxygen 

### ISSUE THREAD

**Issue by dkapil** [SAP/hybris-commerce-eclipse-plugin#29]
When formatting impex, formatter fails and runs into IndexOutOfBoundException at this line 

`at com.hybris.impexformatter.actions.Formatter.formatLines(Formatter.java:173)`

Please view my full error report submitted to eclipse on https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/ToceZYvfRTMSquWA2L0f1OKAwdVJeCMKasLDRVpDpkLXNYQZRMoag3rwvwS08B6i

**Comment by mikolayek** [comment]
Hi. I could not reproduce that issue.
