### ISSUE TITLE
Attribute "startStopThreads" was already specified for element "Host".

### ISSUE THREAD

**Issue by sam19119** [SAP/hybris-commerce-eclipse-plugin#35]
org.apache.catalina.startup.Catalina start
SEVERE: Cannot start server. Server instance is not configured.
<-- Wrapper Stopped

-------
How to solve this issue, when I'm about to start the server I'm getting this error in the terminal.

**Comment by mikolayek** [comment]
Hi there,
issue is on waitlist for next release. 
in the meanwhile, when you import project, just uncheck one option related to Tomcat.

<img width="543" alt="Screenshot 2019-09-07 23 58 19" src="https://user-images.githubusercontent.com/647901/64480642-84e9ec80-d1cb-11e9-83a9-1ee01b52bfa1.png">

**Comment by mikolayek** [comment]
issue fixed #35 in version 1.4.0. Please update plugin
