### ISSUE TITLE
add platform home validation during import

### ISSUE THREAD

**Issue by mikolayek** [SAP/hybris-commerce-eclipse-plugin#38]
during importing project on step1 there is possibility to select directory which is hybris platform folder. There is no validation if selected folder is in fact that one desired for import process.

* Simple verification of folder name and folder content should be done.

**Comment by ravidesai22** [comment]
@mikolayek, there is already a validation for platform directory path like,
![image](https://user-images.githubusercontent.com/1702777/67143030-ba7efc80-f284-11e9-816f-288844aaa2c1.png)

or am I missing something here?

**Comment by mikolayek** [comment]
Hi @ravidesai22, yes, you are right. 
My intention was to have validation run when field is filled, not to wait for last step.
