### ISSUE TITLE
NumberFormatException when importing platform

### ISSUE THREAD

**Issue by raymundojaramillo** [SAP/hybris-commerce-eclipse-plugin#52]
I am seeing the following error when importing a new project in Eclipse 2020-06:

NumberFormatException: multiple points

See attached image for more details

My setup:
Eclipse 2020-06 running on Java 11.0.7 (oracle)
Importing Commerce 6.5.0.3 project which uses Java 1.8.0_171 (oracle)
Mac OS Catalina

**To Reproduce**
1. Go to File / Import
2. in the import wizard , choose SAP/ Import SAP Platform
3. In the next screen, choose to the "platform"  folder of the Commerce installation
4. Leave all options (checkboxes) selected
5. Click Finish
6. The error in the attached screenshot appears (Number format  exception).

**Expected behavior**
The extensions should be successfully imported

**Screenshots**

![image](https://user-images.githubusercontent.com/45374543/93130981-fb4fe300-f698-11ea-8436-e4b90876e869.png)

**Comment by mikolayek** [comment]
issue has been fixed. please install latest 1.5.1 version
