### ISSUE TITLE
Unsupported Class Version Error by Import Hybris Platform with Plugin

### ISSUE THREAD

**Issue by klouisbrother** [SAP/hybris-commerce-eclipse-plugin#67]
Dear Team,

I think I have a related issue of Unsupported Class Version Error by Import Hybris Platform with Plugin:

![image](https://user-images.githubusercontent.com/11328161/99954130-8ed11e80-2d82-11eb-89f8-ec2acbb3b073.png)

Hybris Version: 1905
Eclipse Version: 2019-09 R (4.13.0)
Eclipse Build id: 20190917-1200

Is there already a workaround available to fix this? Thank you!

**Comment by mikolayek** [comment]
Hello, sure.
could you change your jvm you are using for eclipse, and upgrade do JVM 11?

That should help.

**Comment by klouisbrother** [comment]
Hi @mikolayek , I can try - do you have a guideline for me? :) That would help me a lot!

**Comment by klouisbrother** [comment]
Found the solution 👍 
I was taking the JRE 8 to run it. I moved the JAVA_HOME variable to higher priority, as discribed here: https://www.codejava.net/ides/eclipse/how-to-run-eclipse-under-different-version-of-jdk-or-jre

Platform was imported sucessfully :)
