### ISSUE TITLE
Source packages don't show due to bad file extension filter

### ISSUE THREAD

**Issue by stephane-tremblay-hybris** [SAP/hybris-commerce-eclipse-plugin#7]
When importing a Hybris Commerce project into Eclipse using the HyEclipse plugin, in the wizard there is a step where you have the option of using a source archive with the project.

However, the file dialog to select the zip file has a filter for "zip" file extension and no files actually show. You have to put "*" in the file name and press enter to see all the files.

This is because the file filter is missing a period. It should be ".zip" instead of "zip".
![file_dialog](https://user-images.githubusercontent.com/29893917/27833848-755bf41c-60a2-11e7-91f0-328e4ca2acbb.jpg)
![file_dialog_modified](https://user-images.githubusercontent.com/29893917/27833850-7765a744-60a2-11e7-8b73-7a8bf7fb3058.jpg)

**Comment by brendandobbs** [comment]
Fixed in latest 1.4 release
