### ISSUE TITLE
[rl-license_file-3] License still seems to contain an API section. This section needs to be removed!

### ISSUE THREAD

**Issue by mikolayek** [SAP/hybris-commerce-eclipse-plugin#78]
For details please see our wiki page at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-License(rl-license_file-XX)

**Comment by SebastianWolf-SAP** [comment]
This seems to be fixed. Thank you very much!
