### ISSUE TITLE
Plugin loading infinitely while importing 2105 platform

### ISSUE THREAD

**Issue by gandhiharshgit** [SAP/hybris-commerce-eclipse-plugin#92]
**Describe the bug**
When i tried importing sap hybris (commerce) 2105 platform, It is loading infinitely.
In the same eclipse I am able to import 2011 platform.
I am using Eclipse IDE 2021‑09

**To Reproduce**
1) Go to File -> Import.... There you can find category SAP 
2) Click on Import SAP Platform.
3) Keep the checkbox selection default and provide path to - "hybris/bin/platform" folder for your project.

**Expected behavior**
Wizard should import all relevant extension (as defined in localextensions.xml file) in eclipse workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/67458720/133873246-02c12d73-1422-49ee-9ace-b3ac566c97f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Eclipse IDE 2021‑09

**Additional context**
I tried multiple times but was facing same issue for 2105, infact 1 other developer in my team also tried and facing same issue.

**Comment by mikolayek** [comment]
Hi, thank you for your emai.
Can you also provide log file from your eclipse workspace, please?
Thank you

**Comment by gandhiharshgit** [comment]
Hi @mikolayek 

Please find attached log file
[.log](https://github.com/SAP/hybris-commerce-eclipse-plugin/files/7189503/default.log)

I also notice it stuck while loading / resolving smartedittools extension

Thanks you

**Comment by mikolayek** [comment]
hm.. Unfortunately there is nothing in log file. I mean no exception. It is impossible to find where it stuck in fact.

**Comment by mikolayek** [comment]
I am not able to help you with all these information you delivered, unfortunately.

You would need to run it in debug mode or I would need to have an access to your environment locally, which I assume is not possible.

**Comment by gandhiharshgit** [comment]
@mikolayek - Can you please tell me how i launch eclipse in debug mode.
since this issue is happening while importing platform initially.

**Comment by mikolayek** [comment]
Hi @gandhiharshgit, can you update my plugin please?
I have fixed one thing related with project import. that is wild guess, but let's check.
I have bumped eclipse version as a baseline and now it is 2021-06, but you are on newer version, so that should not be an issue.

**Comment by gandhiharshgit** [comment]
Hi @mikolayek, It got stuck again.

![image](https://user-images.githubusercontent.com/67458720/134358502-4ad9f696-d6aa-4266-8e2f-6b97fb2e59f3.png)

My other team members are also facing issues while importing 2105 platform in eclipse

**Comment by mikolayek** [comment]
but have you updated plugin? there has been released v. 1.5.7 yesterday.

**Comment by gandhiharshgit** [comment]
Yes I have updated that today

**Comment by mikolayek** [comment]
OK. Thanks. could you share .log file from workspace, please?
Maybe there will be a rootcause

**Comment by gandhiharshgit** [comment]
Here you go
[.log](https://github.com/SAP/hybris-commerce-eclipse-plugin/files/7215052/default.log)
